Update pr check.yml

diff --git a/.github/workflows/pr check.yml b/.github/workflows/pr check.yml
--- a/.github/workflows/pr check.yml
+++ b/.github/workflows/pr check.yml
@@ -15,32 +15,25 @@ jobs:
         uses: actions/checkout@v5
         with:
           fetch-depth: 0   
-          ref: ${{ github.head_ref }} 
-          
-      - name: Fetch main branch fully
-        run: |
-          git fetch origin main    
-          
-      - name: docker use check
-        id: docker-check
-        continue-on-error: true
-        run: |
-          current_branch=$(git branch --show-current)
-          git checkout origin/main
-          if grep -hiE '\b(docker\s+push|docker/build-push-action|snyk-docker-action)\b' .github/workflows/*.yml --exclude='pr check.yml' | grep -viE '^\s*#'; then
-            exit 1
-          fi
-          git checkout "$current_branch"
-          echo git branch --show-current
+          ref: ${{ github.head_ref }}    
+         
+#      - name: docker use check
+#        id: docker-check
+#        continue-on-error: true
+#        run: |
+#          if grep -hiE '\b(docker\s+push|docker/build-push-action|snyk-docker-action)\b' .github/workflows/*.yml --exclude='pr check.yml' | grep -viE '^\s*#'; then
+#            exit 1
+#          fi
+#          echo 
          
       - name: git diff
         id: diff-check
         continue-on-error: true
-        if: steps.docker-check.outcome == 'failure'
+#        if: steps.docker-check.outcome == 'failure'
         run: |
           set -e
 
-          changed_files=$(git diff --name-only origin/main...HEAD -- '.github/workflows/*.yml')
+          changed_files=$(git diff --name-only origin/main... -- '.github/workflows/*.yml')
           
           if [ -z "$changed_files" ]; then
             echo "No workflow files changed"
